# Generated by Django 5.0.4 on 2024-04-23 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cathegory',
            fields=[
                ('name', models.TextField(max_length=128, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('service_name', models.TextField(max_length=128, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('cathegory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.cathegory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='cathegory',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='cat_unique_for_user'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('service_name', 'user'), name='sub_unique_for_user'),
        ),
    ]
