# Generated by Django 5.0.4 on 2024-04-28 14:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cathegory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='cathegory',
            new_name='category',
        ),
    ]
